# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppOrderFilesSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#pod 'AppOrderFiles'

  target 'AppOrderFilesSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppOrderFilesSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
